"""Phase 5 tests: backup service, restore safety, health page/API, draft
recovery, settings/sidebar integration, and route smoke.

Each test runs against a throwaway SQLite DB and an isolated runtime config
file so running the suite NEVER rewrites the production/local data/config.json
or touches live uploads.

Run with:
    python tests/test_phase5.py
"""

import json
import os
import shutil
import sqlite3
import sys
import tempfile
import zipfile
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)) + "/..")

from starlette.testclient import TestClient  # noqa: E402

import app.database as db  # noqa: E402
from app import backup_service as backup  # noqa: E402
from app import health as health  # noqa: E402
from app.main import app  # noqa: E402

PASS = 0
FAIL = 0

CONFIG_BEFORE = None


def check(label, cond, extra=""):
    global PASS, FAIL
    if cond:
        PASS += 1
        print(f"  [PASS] {label}")
    else:
        FAIL += 1
        print(f"  [FAIL] {label} {extra}")


def fresh_db():
    tmp = tempfile.mkdtemp()
    db.DB_DIR = Path(tmp) / "database"
    db.DB_PATH = db.DB_DIR / "teamhr.db"
    db.init_db()
    os.environ["TEAMHR_CONFIG_FILE"] = str(Path(tmp) / "config.json")
    return tmp


def seed():
    fresh_db()
    db.create_batch("Draft")
    db.insert_candidate({
        "name": "Alpha One", "mobile": "9000000001", "aadhaar_number": "111122223333",
        "address": "42 Alpha Street", "facility_name": "NelamangalaHub_BLR",
        "designation": "LM - Delivery Executive", "cost_code": "4421",
        "status": "ready", "batch_id": 1,
    })
    return TestClient(app)


def test_config_json_unchanged():
    print("data/config.json is never rewritten by phase5 tests")
    global CONFIG_BEFORE
    cfg = Path(__file__).resolve().parent.parent / "data" / "config.json"
    CONFIG_BEFORE = cfg.read_text(encoding="utf-8") if cfg.exists() else None
    seed()
    after = cfg.read_text(encoding="utf-8") if cfg.exists() else None
    check("config.json content unchanged", after == CONFIG_BEFORE)
    check("config.json not introduced if absent",
          (CONFIG_BEFORE is None) == (after is None))


def test_safety_flags_still_false():
    print("Live-upload safety flags remain disabled")
    import app.portal.esampark as e
    check("REAL_UPLOAD_ENABLED is False",
          getattr(e, "REAL_UPLOAD_ENABLED", True) is False)
    check("ESAMPARK_LIVE_TEST_MODE is False",
          getattr(e, "ESAMPARK_LIVE_TEST_MODE", True) is False)


def _cleanup_backup_dir():
    bdir = backup.backup_dir()
    if bdir.exists():
        shutil.rmtree(bdir)
    bdir.mkdir(parents=True, exist_ok=True)
    return bdir


# ── Backup creation ──────────────────────────────────────────────────────────


def test_backup_folder_creation():
    print("create_backup creates backup folder + zip")
    seed()
    bdir = _cleanup_backup_dir()
    r = backup.create_backup()
    check("ok", r.get("ok") is True)
    check("zip exists", (bdir / r["filename"]).exists())
    check("filename prefix", r["filename"].startswith("TeamHR_Backup_"))
    check("had manifest git_commit", "git_commit" in r)
    check("excludes generated by default", r.get("include_generated_files") is False)


def test_backup_manifest_and_checksums():
    print("backup manifest present with SHA-256 checksums")
    seed()
    bdir = _cleanup_backup_dir()
    r = backup.create_backup()
    with zipfile.ZipFile(str(bdir / r["filename"])) as zf:
        names = zf.namelist()
        manifest = json.loads(zf.read("manifest.json").decode("utf-8"))
    check("manifest present", "manifest.json" in names)
    check("db present", "teamhr.db" in names)
    check("backup_version == 1", manifest["backup_version"] == 1)
    check("created_at present", bool(manifest.get("created_at")))
    check("files checksums", "teamhr.db" in manifest["files"])
    check("two entries", len(names) == 2)

    # Verify the checksum actually matches the extracted file.
    tmp = Path(tempfile.mkdtemp())
    with zipfile.ZipFile(str(bdir / r["filename"])) as zf:
        zf.extract("teamhr.db", str(tmp))
    with open(tmp / "teamhr.db", "rb") as fh:
        import hashlib
        sha = hashlib.sha256(fh.read()).hexdigest()
    check("sha256 matches manifest", sha == manifest["files"]["teamhr.db"])


def test_db_integrity_in_backup():
    print("backed-up database passes integrity_check")
    seed()
    bdir = _cleanup_backup_dir()
    r = backup.create_backup()
    tmp = Path(tempfile.mkdtemp())
    with zipfile.ZipFile(str(bdir / r["filename"])) as zf:
        zf.extract("teamhr.db", str(tmp))
    conn = sqlite3.connect(str(tmp / "teamhr.db"))
    try:
        res = conn.execute("PRAGMA integrity_check").fetchone()[0]
    finally:
        conn.close()
    check("integrity ok", res == "ok")


def test_no_secret_or_sensitive_files_in_backup():
    print("backup has no secret/session/raw-document entries")
    seed()
    bdir = _cleanup_backup_dir()
    r = backup.create_backup()
    with zipfile.ZipFile(str(bdir / r["filename"])) as zf:
        names = zf.namelist()
    joined = " ".join(n.lower() for n in names)
    check("only manifest + db", set(names) == {"manifest.json", "teamhr.db"})
    for bad in ("auth_state", "cookie", "session", "aadhaar", ".png", ".jpg",
                ".pdf", "venv", "log"):
        check(f"no {bad!r}", bad not in joined)


def test_generated_files_excluded_default():
    print("generated files excluded by default; optionally included")
    seed()
    bdir = _cleanup_backup_dir()
    import app.generation as gen
    out = Path(gen.get_output_base_dir())
    out.mkdir(parents=True, exist_ok=True)
    (out / "sample.xlsx").write_bytes(b"not-a-real-xlsx")
    r = backup.create_backup(include_generated=False)
    with zipfile.ZipFile(str(bdir / r["filename"])) as zf:
        names = zf.namelist()
    check("generated not included by default", "generated" not in " ".join(names))

    # Optional inclusion.
    r2 = backup.create_backup(include_generated=True)
    with zipfile.ZipFile(str(bdir / r2["filename"])) as zf:
        names2 = zf.namelist()
    check("generated includes file when requested",
          any(n.startswith("generated/") and n.endswith(".xlsx") for n in names2))
    check("manifest flag set",
          r2.get("include_generated_files") is True)


# ── Backup verify ────────────────────────────────────────────────────────────


def test_verify_valid_backup():
    print("verify_valid_backup returns Valid")
    seed()
    bdir = _cleanup_backup_dir()
    r = backup.create_backup()
    v = backup.verify_backup(bdir / r["filename"])
    check("valid", v.get("valid") is True)
    check("status Valid", v.get("status") == "Valid")
    check("manifest returned", "manifest" in v)


def test_verify_corrupt_zip_rejected():
    print("corrupt zip rejected")
    seed()
    bdir = _cleanup_backup_dir()
    p = bdir / "TeamHR_Backup_CORRUPT.zip"
    p.write_bytes(b"definitely not a zip file")
    v = backup.verify_backup(p)
    check("invalid", v.get("valid") is False)
    check("status Invalid", v.get("status") == "Invalid")


def test_verify_checksum_mismatch_rejected():
    print("checksum mismatch rejected")
    seed()
    bdir = _cleanup_backup_dir()
    good = backup.create_backup()["filename"]
    zp = bdir / good
    tmp = Path(tempfile.mkdtemp())
    with zipfile.ZipFile(str(zp)) as zf:
        zf.extractall(str(tmp))
    mf = tmp / "manifest.json"
    m = json.loads(mf.read_text())
    m["files"]["teamhr.db"] = "0" * 64
    mf.write_text(json.dumps(m))
    tampered = bdir / "TeamHR_Backup_TAMPERED.zip"
    with zipfile.ZipFile(str(tampered), "w") as zf:
        zf.write(mf, "manifest.json")
        zf.write(tmp / "teamhr.db", "teamhr.db")
    v = backup.verify_backup(tampered)
    check("invalid", v.get("valid") is False)
    check("contains checksum", "checksum" in (v.get("error") or "").lower())


def test_verify_missing_manifest_rejected():
    print("missing manifest rejected")
    seed()
    bdir = _cleanup_backup_dir()
    p = bdir / "TeamHR_Backup_NOMANIFEST.zip"
    with zipfile.ZipFile(str(p), "w") as zf:
        zf.writestr("teamhr.db", "not a db")
    v = backup.verify_backup(p)
    check("invalid", v.get("valid") is False)
    check("mentions manifest", "manifest" in (v.get("error") or "").lower())


def test_verify_unsupported_version_rejected():
    print("unsupported backup_version rejected")
    seed()
    bdir = _cleanup_backup_dir()
    r = backup.create_backup()
    zp = bdir / r["filename"]
    tmp = Path(tempfile.mkdtemp())
    with zipfile.ZipFile(str(zp)) as zf:
        zf.extractall(str(tmp))
    mf = tmp / "manifest.json"
    m = json.loads(mf.read_text())
    m["backup_version"] = 999
    mf.write_text(json.dumps(m))
    bad = bdir / "TeamHR_Backup_BADVERSION.zip"
    with zipfile.ZipFile(str(bad), "w") as zf:
        zf.write(mf, "manifest.json")
        zf.write(tmp / "teamhr.db", "teamhr.db")
    v = backup.verify_backup(bad)
    check("invalid", v.get("valid") is False)
    check("mentions version", "version" in (v.get("error") or "").lower())


# ── Restore ──────────────────────────────────────────────────────────────────


def test_restore_invalid_blocked():
    print("restore invalid backup is blocked")
    seed()
    bdir = _cleanup_backup_dir()
    p = bdir / "TeamHR_Backup_CORRUPT.zip"
    p.write_bytes(b"not a zip")
    r = backup.restore_backup(p.name)
    check("blocked", r.get("ok") is False)
    check("stage verify", r.get("stage") == "verify")


def test_restore_pre_restore_backup_created():
    print("restore creates pre-restore backup + reverts DB")
    seed()
    bdir = _cleanup_backup_dir()
    good = backup.create_backup()["filename"]
    # Now mutate the live DB (extra candidate) AFTER the good backup.
    db.insert_candidate({"name": "EXTRA", "mobile": "9000000999",
                         "status": "ready", "batch_id": 1})
    check("live has 2 before restore", len(db.list_candidates()) == 2)
    rr = backup.restore_backup(good)
    check("restore ok", rr.get("ok") is True)
    check("pre-restore recorded", bool(rr.get("pre_restore")))
    check("pre-restore file exists", (bdir / rr["pre_restore"]).exists())
    check("pre-restore distinct from source", rr["pre_restore"] != good)
    check("candidates back to 1", len(db.list_candidates()) == 1)

    # The pre-restore backup must contain the 2-candidate (post-mutation) DB,
    # proving it snapshot the current state before the swap.
    tmp = Path(tempfile.mkdtemp())
    with zipfile.ZipFile(str(bdir / rr["pre_restore"])) as zf:
        zf.extract("teamhr.db", str(tmp))
    conn = sqlite3.connect(str(tmp / "teamhr.db"))
    try:
        pre_count = conn.execute("SELECT COUNT(*) FROM candidates").fetchone()[0]
    finally:
        conn.close()
    check("pre-restore db captured 2 candidates", pre_count == 2)

    # Restore Completed is recorded into the restored DB after the swap.
    events = [e["event_type"] for e in db.list_system_events()]
    check("audit event Restore Completed", "Restore Completed" in events)


def test_restore_does_not_run_live_portal():
    print("restore does not attempt live eSampark interaction")
    seed()
    bdir = _cleanup_backup_dir()
    good = backup.create_backup()["filename"]
    rr = backup.restore_backup(good)
    check("restore ok", rr.get("ok") is True)


def test_restore_requires_final_file_not_found():
    print("missing backup file returns structured error")
    seed()
    r = backup.restore_backup("TeamHR_Backup_DOES_NOT_EXIST.zip")
    check("blocked", r.get("ok") is False)
    check("stage locate", r.get("stage") == "locate")


# ── Health ───────────────────────────────────────────────────────────────────


def test_health_page_200():
    print("/health renders 200 with status cards")
    client = seed()
    r = client.get("/health")
    check("status 200", r.status_code == 200)
    for frag in ("Database", "Database Integrity", "Facility Master",
                 "Designation Master", "Admin Master", "OCR Backend",
                 "Generated Folder", "Backup Folder", "Portal Selectors",
                 "Live Upload Safety", "Config", "Disk Space", "Last Backup",
                 "Application Version"):
        check(f"card {frag}", frag in r.text)


def test_health_no_secrets():
    print("health page/api expose no secrets or local env paths")
    client = seed()
    html = client.get("/health").text
    api = client.get("/api/health").json()
    for bad in ("auth_state", "password", "token", "credential", "api_key",
                "aadhaar_number", "111122223333", "42 Alpha Street"):
        check(f"health html no {bad!r}", bad not in html)
    check("health api no secrets", all("aadhaar" not in str(k).lower()
                                       for k in api.keys()))


def test_health_api_safe_shape():
    print("/api/health returns safe non-secret JSON")
    client = seed()
    d = client.get("/api/health").json()
    check("database key", "database" in d)
    check("masters key", "masters" in d)
    check("ocr key", "ocr" in d)
    check("live_upload locked", d.get("live_upload") == "locked")
    check("backup key", "backup" in d)
    check("disk_space key", "disk_space" in d)


def test_health_db_and_master_status():
    print("health reports DB + master status")
    client = seed()
    d = client.get("/api/health").json()
    check("database ok", d.get("database") == "ok")
    check("masters ok/warning", d.get("masters") in ("ok", "warning"))


def test_health_last_backup_and_disk():
    print("health reports last backup + disk status")
    client = seed()
    bdir = backup.backup_dir()
    bdir.mkdir(parents=True, exist_ok=True)
    backup.create_backup()
    hr = health.build_health_report()
    cards = {c["name"]: c for c in hr["cards"]}
    check("last backup card present", cards.get("Last Backup", {}).get("status") == "OK")
    check("disk card present", "Disk Space" in cards)
    d = client.get("/api/health").json()
    check("backup ok", d.get("backup") == "ok")


# ── Drafts ───────────────────────────────────────────────────────────────────


def test_draft_create_update_resume_discard():
    print("candidate_drafts create/update/resume/discard")
    client = seed()
    r = client.post("/api/drafts", json={
        "draft_type": "manual_entry",
        "safe_payload": {"candidate_name": "Draft One", "mobile": "9000000007"},
    })
    check("created", r.status_code == 200 and r.json().get("ok"))
    did = r.json()["draft_id"]
    r = client.post("/api/drafts", json={
        "draft_type": "manual_entry", "draft_id": did,
        "safe_payload": {"candidate_name": "Draft One Updated", "mobile": "9000000008"},
    })
    check("updated ok", r.status_code == 200 and r.json().get("ok"))
    res = client.get("/api/drafts?draft_type=manual_entry").json()
    check("resume lists draft", len(res["drafts"]) == 1)
    r = client.post("/api/drafts/discard", json={"draft_id": did})
    check("discarded", r.json().get("ok") is True)
    res = client.get("/api/drafts?draft_type=manual_entry").json()
    check("draft gone", len(res["drafts"]) == 0)


def test_draft_rejects_sensitive_payload():
    print("drafts never persist aadhaar/address")
    client = seed()
    client.post("/api/drafts", json={
        "draft_type": "manual_entry",
        "safe_payload": {"candidate_name": "Secret", "address": "42 Secret St",
                         "aadhaar_number": "111122223333"},
    })
    res = client.get("/api/drafts?draft_type=manual_entry").json()
    payload = json.dumps(res["drafts"][0]["safe_payload"])
    check("no address", "42 Secret St" not in payload)
    check("no aadhaar", "111122223333" not in payload)


def test_drafts_absent_from_global_search_dashboard_health():
    print("drafts are absent from search, dashboard and health")
    client = seed()
    client.post("/api/drafts", json={
        "draft_type": "manual_entry",
        "safe_payload": {"candidate_name": "Draft Searchable Name", "mobile": "9000000111"},
    })
    search = client.get("/api/search?q=Draft+Searchable").text
    check("not in global search", "Draft Searchable" not in search)
    dashboard = client.get("/").text
    check("not in dashboard", "Draft Searchable" not in dashboard)
    health_html = client.get("/health").text
    check("not in health", "Draft Searchable" not in health_html)


def test_smart_upload_draft():
    print("smart_upload draft created/resumed/discarded")
    client = seed()
    r = client.post("/api/drafts", json={
        "draft_type": "smart_upload",
        "safe_payload": {"name": "Smart Draft", "mobile": "9000000222"},
    })
    did = r.json()["draft_id"]
    res = client.get("/api/drafts?draft_type=smart_upload").json()
    check("smart draft listed", res["drafts"][0]["draft_type"] == "smart_upload")
    check("smart draft payload", res["drafts"][0]["safe_payload"].get("name") == "Smart Draft")
    r = client.post("/api/drafts/discard", json={"draft_id": did})
    check("discarded", r.json().get("ok") is True)


# ── Settings / sidebar ───────────────────────────────────────────────────────


def test_settings_links_render():
    print("settings shows backup/health links + summary")
    client = seed()
    r = client.get("/settings")
    check("status 200", r.status_code == 200)
    check("backup link", "/backups" in r.text)
    check("health link", "/health" in r.text)
    check("last backup label", "Last:" in r.text)


def test_sidebar_links():
    print("sidebar renders backup/health links under System")
    client = seed()
    r = client.get("/")
    check("backup link", "/backups" in r.text)
    check("health link", "/health" in r.text)


def test_no_dead_links():
    print("new routes all return 200")
    client = seed()
    ok = ["/backups", "/health", "/settings", "/"]
    for u in ok:
        r = client.get(u)
        check(f"GET {u} -> 200", r.status_code == 200, f"got {r.status_code}")


# ── Route smoke ──────────────────────────────────────────────────────────────


def test_route_smoke():
    print("full route smoke")
    client = seed()
    cid = db.list_candidates()[0]["candidate_id"]
    urls = ["/", "/candidates", "/pipeline", "/batch-review",
            "/backups", "/health", "/settings", "/smart-upload",
            "/manual-entry", "/portal", "/live-upload",
            "/admin/master-data", "/validation", "/reports", "/data-quality",
            f"/candidates/{cid}", "/batches/1"]
    for u in urls:
        r = client.get(u)
        check(f"GET {u} -> 200", r.status_code == 200, f"got {r.status_code}")


def test_js_syntax():
    print("JS syntax checks")
    import subprocess
    base = Path(__file__).resolve().parent.parent / "app" / "static"
    for fn in ("manual_entry.js", "ui.js", "app.js"):
        p = base / fn
        if not p.exists():
            continue
        pr = subprocess.run(["node", "--check", str(p)],
                            capture_output=True, text=True)
        check(f"{fn} syntax OK", pr.returncode == 0, pr.stderr[:200])


def run_all():
    global PASS, FAIL
    print("=" * 60)
    print("PHASE 5: BACKUP / RESTORE / HEALTH / DRAFTS")
    print("=" * 60)
    test_config_json_unchanged()
    test_safety_flags_still_false()
    test_backup_folder_creation()
    test_backup_manifest_and_checksums()
    test_db_integrity_in_backup()
    test_no_secret_or_sensitive_files_in_backup()
    test_generated_files_excluded_default()
    test_verify_valid_backup()
    test_verify_corrupt_zip_rejected()
    test_verify_checksum_mismatch_rejected()
    test_verify_missing_manifest_rejected()
    test_verify_unsupported_version_rejected()
    test_restore_invalid_blocked()
    test_restore_pre_restore_backup_created()
    test_restore_does_not_run_live_portal()
    test_restore_requires_final_file_not_found()
    test_health_page_200()
    test_health_no_secrets()
    test_health_api_safe_shape()
    test_health_db_and_master_status()
    test_health_last_backup_and_disk()
    test_draft_create_update_resume_discard()
    test_draft_rejects_sensitive_payload()
    test_drafts_absent_from_global_search_dashboard_health()
    test_smart_upload_draft()
    test_settings_links_render()
    test_sidebar_links()
    test_no_dead_links()
    test_route_smoke()
    test_js_syntax()
    print("=" * 60)
    print(f"RESULT: {PASS} passed, {FAIL} failed")
    if FAIL:
        sys.exit(1)


if __name__ == "__main__":
    run_all()