"""UAT (Manual Acceptance Test) catalog.

Defines all test groups and test cases for the TeamHR Manual Acceptance Test.
Each group has a key, label, and ordered list of (test_id, test_name) tuples.
"""

UAT_GROUPS = [
    {
        "key": "A",
        "label": "Application / Navigation",
        "tests": [
            ("A01", "Dashboard loads"),
            ("A02", "Sidebar links work"),
            ("A03", "Global search opens"),
            ("A04", "Search by candidate name"),
            ("A05", "Search by mobile"),
            ("A06", "Search by facility"),
            ("A07", "Search by role"),
            ("A08", "Search does not expose Aadhaar"),
            ("A09", "Search does not expose address"),
            ("A10", 'Keyboard "/" or Ctrl+K focuses search'),
        ],
    },
    {
        "key": "B",
        "label": "Smart Upload",
        "tests": [
            ("B01", "Smart Upload page loads"),
            ("B02", "Aadhaar image upload works"),
            ("B03", "Recruiter screenshot upload works"),
            ("B04", "OCR completes"),
            ("B05", "Candidate name is correctly extracted"),
            ("B06", "DOB correctly extracted"),
            ("B07", "Aadhaar correctly extracted for review"),
            ("B08", "Address correctly extracted"),
            ("B09", "Mobile normalized correctly"),
            ("B10", "Entity inferred correctly"),
            ("B11", "Operation LM/FM correctly resolved"),
            ("B12", "Cost code correctly resolved"),
            ("B13", "Role correctly resolved"),
            ("B14", "Facility correctly resolved"),
            ("B15", "Location correctly populated"),
            ("B16", "Salary correctly normalized"),
            ("B17", "Evidence/Why section understandable"),
            ("B18", "Needs Review appears for ambiguity"),
            ("B19", "Candidate can be approved after correction"),
            ("B20", "Draft recovery works"),
        ],
    },
    {
        "key": "C",
        "label": "Manual Entry",
        "tests": [
            ("C01", "Manual Entry loads"),
            ("C02", "Candidate can be manually created"),
            ("C03", "Cost code derives from entity/operation"),
            ("C04", "Role master dropdown correct"),
            ("C05", "Facility master dropdown correct"),
            ("C06", "Location auto-populates"),
            ("C07", "Salary validation works"),
            ("C08", "Mobile validation works"),
            ("C09", "Candidate edit mode works"),
            ("C10", "Manual draft recovery works"),
        ],
    },
    {
        "key": "D",
        "label": "Candidate Management",
        "tests": [
            ("D01", "Candidate list loads"),
            ("D02", "Candidate View opens detail page"),
            ("D03", "Edit opens manual-entry edit"),
            ("D04", "Previous candidate works"),
            ("D05", "Next candidate works"),
            ("D06", "Candidate timeline displays"),
            ("D07", "Edit event appears in timeline"),
            ("D08", "Aadhaar visible only on detail page"),
            ("D09", "Address visible only on detail page"),
            ("D10", "Evidence panel works"),
            ("D11", "Document section works"),
            ("D12", "Review summary correct"),
            ("D13", "Saved views create"),
            ("D14", "Saved views rename"),
            ("D15", "Saved views delete"),
            ("D16", "Status filters work"),
        ],
    },
    {
        "key": "E",
        "label": "Bulk Actions",
        "tests": [
            ("E01", "Select multiple candidates"),
            ("E02", "Mark selected Needs Review"),
            ("E03", "Add Ready candidates to batch"),
            ("E04", "Invalid candidate blocked from batch"),
            ("E05", "Export selected works"),
            ("E06", "Export excludes Aadhaar"),
            ("E07", "Export excludes address"),
            ("E08", "No bulk portal upload available"),
        ],
    },
    {
        "key": "F",
        "label": "Batches",
        "tests": [
            ("F01", "Batch Review loads"),
            ("F02", "Batch can be created from Ready candidates"),
            ("F03", "Batch Detail opens"),
            ("F04", "Candidate count correct"),
            ("F05", "Needs Review candidate excluded/flagged correctly"),
            ("F06", "Candidate to Batch link works"),
            ("F07", "Batch to Candidate link works"),
            ("F08", "Generate Excel works"),
            ("F09", "Generated filename correct"),
            ("F10", "Generated workbook opens"),
            ("F11", "Workbook contains correct candidate data"),
            ("F12", "Daily master generated correctly"),
            ("F13", "Daily master Aadhaar remains masked"),
            ("F14", "Batch timeline displays"),
            ("F15", "Generated file appears on candidate detail"),
        ],
    },
    {
        "key": "G",
        "label": "Pipeline",
        "tests": [
            ("G01", "Pipeline page loads"),
            ("G02", "Draft column correct"),
            ("G03", "Needs Review column correct"),
            ("G04", "Ready column correct"),
            ("G05", "Generated column correct"),
            ("G06", "Portal Pending column correct"),
            ("G07", "Portal Success column correct"),
            ("G08", "Portal Failed column correct"),
            ("G09", "Candidate counts correct"),
            ("G10", "Pipeline filters work"),
            ("G11", "Pipeline search works"),
            ("G12", "Candidate card opens detail"),
            ("G13", "Portal columns are read-only"),
        ],
    },
    {
        "key": "H",
        "label": "Data Quality",
        "tests": [
            ("H01", "Data Quality page loads"),
            ("H02", "Missing field counts correct"),
            ("H03", "Duplicate mobile detection works"),
            ("H04", "Missing facility drill-down works"),
            ("H05", "Invalid salary drill-down works"),
            ("H06", "Needs Review drill-down works"),
            ("H07", "Candidate View works"),
            ("H08", "No Aadhaar exposed"),
            ("H09", "No address exposed"),
        ],
    },
    {
        "key": "I",
        "label": "Admin Master",
        "tests": [
            ("I01", "Admin Master page loads"),
            ("I02", "Add Flipkart LM facility"),
            ("I03", "Add Flipkart FM facility"),
            ("I04", "Add Myntra LM facility"),
            ("I05", "Cost code derives correctly"),
            ("I06", "Add role"),
            ("I07", "Add role aliases"),
            ("I08", "Role compatibility works"),
            ("I09", "Search works"),
            ("I10", "Filters work"),
            ("I11", "Sort works"),
            ("I12", "Pagination works"),
            ("I13", "Deactivate facility"),
            ("I14", "Reactivate facility"),
            ("I15", "Excel master remains unchanged"),
            ("I16", "Admin override works"),
            ("I17", "Import preview works"),
            ("I18", "Preview does not mutate data"),
            ("I19", "Change history recorded"),
            ("I20", "Admin-added facility resolves in Smart Upload"),
        ],
    },
    {
        "key": "J",
        "label": "Backup / Restore",
        "tests": [
            ("J01", "Backup page loads"),
            ("J02", "Create backup works"),
            ("J03", "Backup appears in history"),
            ("J04", "Verify backup succeeds"),
            ("J05", "Manifest exists"),
            ("J06", "Checksums verify"),
            ("J07", "Generated Excel excluded by default"),
            ("J08", "Raw Aadhaar documents excluded"),
            ("J09", "Corrupt backup rejected"),
            ("J10", "Restore requires confirmation"),
            ("J11", "Pre-restore backup created"),
            ("J12", "Restore succeeds on controlled test"),
            ("J13", "Safety flags remain disabled after restore"),
        ],
    },
    {
        "key": "K",
        "label": "Health",
        "tests": [
            ("K01", "Health page loads"),
            ("K02", "Database OK"),
            ("K03", "DB integrity OK"),
            ("K04", "Designation master OK"),
            ("K05", "Facility master OK"),
            ("K06", "Admin master OK"),
            ("K07", "OCR backend OK"),
            ("K08", "Generated folder OK"),
            ("K09", "Backup folder OK"),
            ("K10", "Portal selectors loaded"),
            ("K11", "Live Upload shows LOCKED"),
            ("K12", "Disk information shown"),
            ("K13", "Last Backup shown"),
            ("K14", "No secrets exposed"),
        ],
    },
    {
        "key": "L",
        "label": "Live Upload Safety",
        "tests": [
            ("L01", "Live Upload page loads"),
            ("L02", "REAL_UPLOAD_ENABLED shows false"),
            ("L03", "ESAMPARK_LIVE_TEST_MODE shows false"),
            ("L04", "Upload button blocked"),
            ("L05", "Single-candidate guard visible"),
            ("L06", "Manual checklist visible"),
            ("L07", "Two-step confirmation exists"),
            ("L08", "Duplicate submission guard exists"),
            ("L09", "Portal status/history page loads"),
            ("L10", "No automatic retry behavior exposed"),
        ],
    },
    {
        "key": "M",
        "label": "Validation",
        "tests": [
            ("M01", "Validation page loads"),
            ("M02", "Set A available"),
            ("M03", "Set B = pass"),
            ("M04", "Set C = pass"),
            ("M05", "Wrong Auto-Decision Rate remains 0% for B"),
            ("M06", "Wrong Auto-Decision Rate remains 0% for C"),
            ("M07", "All Sets view works"),
        ],
    },
    {
        "key": "N",
        "label": "Reports / Settings",
        "tests": [
            ("N01", "Reports page loads"),
            ("N02", "Settings page loads"),
            ("N03", "Master status correct"),
            ("N04", "Admin Master counts correct"),
            ("N05", "Backup status correct"),
            ("N06", "Health link works"),
            ("N07", "No dead sidebar links"),
        ],
    },
]

# Flat lookup: test_id -> (group_key, test_name)
UAT_TEST_LOOKUP: dict[str, tuple[str, str]] = {}
for _g in UAT_GROUPS:
    for _tid, _tname in _g["tests"]:
        UAT_TEST_LOOKUP[_tid] = (_g["key"], _tname)

# Total number of UAT tests
UAT_TOTAL = sum(len(g["tests"]) for g in UAT_GROUPS)
