from __future__ import annotations

# AUTO-GENERATED by TeamHR portal verifiers (Stage 4B/4C/4D) — do not edit by hand.
# Live-verified eSampark selectors confirmed against the REAL portal DOM.
# Consumed by app/portal/selectors.py (prepended as prioritized primaries).
# No secrets are stored here.

VERIFIED = {
    'FILE_INPUT': 'input[type="file"]',
    'UPLOAD_SUBMIT': 'button:has-text("Upload")',
    'UPLOAD_HISTORY': 'text="Upload History"',
    'HISTORY_ROW': 'table tr',
    'HISTORY_FILENAME_CELL': 'td a:has-text("xlsx")',
    'HISTORY_REFERENCE': 'a[href*="download?id="]',
    'HISTORY_ACTION': 'a[href*="download" i]',
}
